name: Code Analyze

on:
  pull_request:
    branches:
      - '*'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Cache Gradle Files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle
      - name: Run Gradle tasks
        run: ./gradlew detekt
      - name: Stop Gradle
        run: ./gradlew --stop
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v1
        if: ${{ always() }}
        with:
          sarif_file: app/build/reports/detekt/detekt.sarif
